# Generated by Django 4.1.5 on 2023-01-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_artist_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='condition',
            new_name='genre',
        ),
        migrations.RemoveField(
            model_name='album',
            name='edtition',
        ),
        migrations.AddField(
            model_name='album',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
