# Generated by Django 4.1.5 on 2023-01-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_rename_condition_album_genre_remove_album_edtition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date_added',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
