# Generated by Django 4.1.5 on 2023-01-04 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_album_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='language',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='album',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='album',
            name='image',
        ),
        migrations.RemoveField(
            model_name='album',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='album',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='album',
            name='title',
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('RK', 'Rock'), ('JZ', 'Jazz'), ('MT', 'Metal'), ('PO', 'Pop'), ('AL', 'Alternative'), ('HH', 'Hip-Hop/Rap'), ('CO', 'Country')], max_length=2)),
                ('language', models.CharField(max_length=200)),
                ('release_date', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
