# Generated by Django 4.1.5 on 2023-01-04 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_album_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
    ]
