# Generated by Django 4.1.5 on 2023-01-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_alter_song_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
